#!/bin/sh
set -e
. /usr/share/debconf/confmodule
if [ "$1" = "configure" -a ! -z "$2" ] && \
   dpkg --compare-versions "$2" lt 0.8; then
	db_input critical isync/upgrade_0.8 || true
	db_go || true
fi
